### ISSUE TITLE
我安装Email模块的时候出现的错误代码

### ISSUE THREAD

**Issue by chenxi456** [brainiac19/SuperStarInfoFetch#2]
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting email
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/71/e7/816030d3b0426c130040bd068be62b9213357ed02896f5d9badcf46d1b5f/email-4.0.2.tar.gz (1.2 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [1 lines of output]
  ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by brainiac19** [comment]
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple Collecting email Using cached https://pypi.tuna.tsinghua.edu.cn/packages/71/e7/816030d3b0426c130040bd068be62b9213357ed02896f5d9badcf46d1b5f/email-4.0.2.tar.gz (1.2 MB) Preparing metadata (setup.py): started Preparing metadata (setup.py): finished with status 'error'
> 
> error: subprocess-exited-with-error
> 
> python setup.py egg_info did not run successfully. exit code: 1
> 
> [1 lines of output] ERROR: Can not execute `setup.py` since setuptools is not available in the build environment. [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> Encountered error while generating package metadata.
> 
> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

优先考虑网络环境是否科学 再者第三方包就算有问题我也处理不了
